<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>BalanceTest</AssemblyName>
    <RootNamespace>IamItem.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\src\Balance.cs" />
  </ItemGroup>
</Project>
